export const PROVIDER_SYMBOLS = {
    TRAILMIXCMS_CMS_ACCOUNT_CONFIG: 'TRAILMIXCMS_CMS_ACCOUNT_CONFIG',
    TRAILMIXCMS_CMS_ACCOUNT_SCHEMA: 'TRAILMIXCMS_CMS_ACCOUNT_SCHEMA',
    TRAILMIXCMS_CMS_ACCOUNT_SETUP: 'TRAILMIXCMS_CMS_ACCOUNT_SETUP',
    TRAILMIXCMS_CMS_ACCOUNT_DTO_SCHEMA: 'TRAILMIXCMS_CMS_ACCOUNT_DTO_SCHEMA',
    TRAILMIXCMS_CMS_ACCOUNT_MAP_ENTITY: 'TRAILMIXCMS_CMS_ACCOUNT_MAP_ENTITY',
    TRAILMIXCMS_CMS_FILE_CONFIG: 'TRAILMIXCMS_CMS_FILE_CONFIG',
    TRAILMIXCMS_CMS_FILE_SCHEMA: 'TRAILMIXCMS_CMS_FILE_SCHEMA',
    TRAILMIXCMS_CMS_FILE_SETUP: 'TRAILMIXCMS_CMS_FILE_SETUP',
    TRAILMIXCMS_CMS_TEXT_CONFIG: 'TRAILMIXCMS_CMS_TEXT_CONFIG',
    TRAILMIXCMS_CMS_TEXT_SCHEMA: 'TRAILMIXCMS_CMS_TEXT_SCHEMA',
    TRAILMIXCMS_CMS_TEXT_SETUP: 'TRAILMIXCMS_CMS_TEXT_SETUP',
    TRAILMIXCMS_CMS_AUTH_GUARD_HOOK: 'TRAILMIXCMS_CMS_AUTH_GUARD_HOOK',
} as const;